# Generated by Django 6.0.4 on 2026-04-12 19:24

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(db_column='id_empresa', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(db_column='id_perfil', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='senha_hash', max_length=128)),
                ('nome', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('data_criacao', models.DateTimeField(db_column='data_criacao', default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acesso', null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', accounts.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id_filial', models.AutoField(db_column='id_filial', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='accounts.empresa')),
            ],
            options={
                'db_table': 'filial',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(db_column='id_setor', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(db_column='id_filial', on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='accounts.filial')),
            ],
            options={
                'db_table': 'setor',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAcesso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='acessos', to='accounts.empresa')),
                ('filial', models.ForeignKey(blank=True, db_column='id_filial', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acessos', to='accounts.filial')),
                ('perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.PROTECT, related_name='acessos', to='accounts.perfil')),
                ('setor', models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acessos', to='accounts.setor')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='acessos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_acesso',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa', 'filial', 'setor'), name='uq_usuario_acesso'), models.CheckConstraint(condition=models.Q(models.Q(('setor__isnull', True), models.Q(('filial__isnull', False), ('empresa__isnull', False)), _connector='OR'), models.Q(('filial__isnull', True), ('empresa__isnull', False), _connector='OR')), name='chk_hierarquia_acesso')],
            },
        ),
    ]
