# Generated by Django 5.2.14 on 2026-05-23 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'db_table': 'chatbot_session',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id_message', models.AutoField(db_column='id_message', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=20, verbose_name='Papel')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Ferramenta')),
                ('tool_parameters', models.JSONField(blank=True, null=True, verbose_name='Parâmetros da Ferramenta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'chatbot_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-last_activity'], name='idx_session_user_activity'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='idx_message_session_time'),
        ),
    ]
