# Generated by Django 6.0.4 on 2026-09-10 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatsession_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrapeVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Uva')),
                ('color', models.CharField(choices=[('tinta', 'Tinta'), ('branca', 'Branca'), ('rosa', 'Rosada')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'chatbot_grape_variety',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vinho')),
                ('color', models.CharField(choices=[('tinto', 'Tinto'), ('branco', 'Branco'), ('rose', 'Rosé'), ('espumante', 'Espumante')], max_length=12)),
                ('sweetness', models.CharField(choices=[('seco', 'Seco'), ('meio_seco', 'Meio seco'), ('suave', 'Suave'), ('doce', 'Doce')], max_length=12)),
                ('alcohol_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False, help_text='Indica que o registro foi criado apenas para testes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_wine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='País')),
                ('iso_code', models.CharField(max_length=2, unique=True, verbose_name='Código ISO')),
            ],
            options={
                'db_table': 'chatbot_wine_country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Produtor')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'chatbot_wine_producer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineGrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wine_links', to='chatbot.grapevariety')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grape_links', to='chatbot.wine')),
            ],
            options={
                'db_table': 'chatbot_wine_grape',
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='grapes',
            field=models.ManyToManyField(related_name='wines', through='chatbot.WineGrape', to='chatbot.grapevariety'),
        ),
        migrations.CreateModel(
            name='WineOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintage_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='chatbot.wine')),
            ],
            options={
                'db_table': 'chatbot_wine_offer',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='chatbot.wineproducer'),
        ),
        migrations.CreateModel(
            name='WineRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Região')),
                ('climate', models.CharField(blank=True, max_length=120, verbose_name='Clima')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='chatbot.winecountry')),
            ],
            options={
                'db_table': 'chatbot_wine_region',
                'ordering': ['country__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='wineproducer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producers', to='chatbot.wineregion'),
        ),
        migrations.CreateModel(
            name='WineReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=120)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='chatbot.wine')),
            ],
            options={
                'db_table': 'chatbot_wine_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='winegrape',
            constraint=models.UniqueConstraint(fields=('wine', 'grape'), name='uq_wine_grape'),
        ),
        migrations.AddConstraint(
            model_name='winegrape',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), models.Q(('percentage__gte', 0), ('percentage__lte', 100)), _connector='OR'), name='ck_wine_grape_percentage'),
        ),
        migrations.AddIndex(
            model_name='wineoffer',
            index=models.Index(fields=['active', 'price'], name='idx_wine_offer_price'),
        ),
        migrations.AddConstraint(
            model_name='wineoffer',
            constraint=models.UniqueConstraint(fields=('wine', 'vintage_year'), name='uq_wine_offer_vintage'),
        ),
        migrations.AddConstraint(
            model_name='wineoffer',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ck_wine_offer_price'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['name'], name='idx_wine_name'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['color', 'sweetness'], name='idx_wine_style'),
        ),
        migrations.AddConstraint(
            model_name='wine',
            constraint=models.UniqueConstraint(fields=('producer', 'name'), name='uq_wine_producer_name'),
        ),
        migrations.AddConstraint(
            model_name='wineregion',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='uq_wine_region_country_name'),
        ),
        migrations.AddIndex(
            model_name='winereview',
            index=models.Index(fields=['wine', '-score'], name='idx_wine_review_score'),
        ),
        migrations.AddConstraint(
            model_name='winereview',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 5)), name='ck_wine_review_score'),
        ),
    ]
